--
-- PostgreSQL database dump
--

\restrict DGp3k5VApZG8XP99JTJm4l0Pe4h7OkaXtC9j0iRe1vBeb8HmxZfOX8lIj0mE7BN

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.9 (Homebrew)

-- Started on 2026-03-19 01:25:45 IST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 41936)
-- Name: academic_years; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.academic_years (
    academic_year_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    academic_year_public_id uuid,
    end_date date,
    is_current boolean,
    label character varying(255),
    start_date date,
    tenant_id bigint
);


ALTER TABLE public.academic_years OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 41935)
-- Name: academic_years_academic_year_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.academic_years ALTER COLUMN academic_year_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_years_academic_year_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 41942)
-- Name: announcements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.announcements (
    announcement_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    announcement_public_id uuid,
    audience character varying(255),
    audience_ref_id bigint,
    content character varying(255),
    expires_at timestamp(6) with time zone,
    pinned_until date,
    priority character varying(255),
    published_at timestamp(6) with time zone,
    tenant_id bigint,
    title character varying(255)
);


ALTER TABLE public.announcements OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 41941)
-- Name: announcements_announcement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.announcements ALTER COLUMN announcement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcements_announcement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 41950)
-- Name: attendance_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance_records (
    attendance_record_id bigint NOT NULL,
    attendance_record_public_id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    is_deleted boolean NOT NULL,
    marked_at timestamp(6) without time zone,
    marked_by bigint NOT NULL,
    remarks character varying(255),
    session_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    student_id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    CONSTRAINT attendance_records_status_check CHECK (((status)::text = ANY ((ARRAY['PRESENT'::character varying, 'ABSENT'::character varying, 'LATE'::character varying, 'EXCUSED'::character varying])::text[])))
);


ALTER TABLE public.attendance_records OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 41949)
-- Name: attendance_records_attendance_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attendance_records ALTER COLUMN attendance_record_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_records_attendance_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 41959)
-- Name: attendance_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance_sessions (
    session_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    conducted_by bigint,
    course_assignment_id bigint,
    end_time time(6) without time zone,
    room_id bigint,
    session_date date,
    session_public_id uuid,
    session_type character varying(255),
    slot_id bigint,
    start_time time(6) without time zone,
    tenant_id bigint,
    topic_covered character varying(255)
);


ALTER TABLE public.attendance_sessions OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 41958)
-- Name: attendance_sessions_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attendance_sessions ALTER COLUMN session_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_sessions_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 41967)
-- Name: batches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.batches (
    batch_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    academic_year_id bigint,
    batch_public_id uuid,
    class_teacher_id bigint,
    current_semester integer,
    max_students integer,
    name character varying(255),
    program_id bigint,
    tenant_id bigint
);


ALTER TABLE public.batches OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 41966)
-- Name: batches_batch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.batches ALTER COLUMN batch_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.batches_batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 41973)
-- Name: course_assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_assignments (
    course_assignment_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    academic_year_id bigint,
    batch_id bigint,
    course_assignment_public_id uuid,
    course_id bigint,
    faculty_id bigint,
    is_primary boolean,
    section character varying(255),
    semester_number integer,
    tenant_id bigint
);


ALTER TABLE public.course_assignments OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 41972)
-- Name: course_assignments_course_assignment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_assignments ALTER COLUMN course_assignment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_assignments_course_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 41979)
-- Name: courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses (
    course_id bigint NOT NULL,
    is_active boolean,
    code character varying(255),
    name character varying(255),
    course_public_id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    created_by bigint,
    credits integer,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    department_id bigint,
    description character varying(255),
    is_deleted boolean NOT NULL,
    lab_hours_per_week integer,
    lecture_hours_per_week integer,
    course_type character varying(255),
    tenant_id uuid,
    tutorial_hours_per_week integer,
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    CONSTRAINT courses_course_type_check CHECK (((course_type)::text = ANY ((ARRAY['COMPULSORY'::character varying, 'OPTIONAL'::character varying])::text[])))
);


ALTER TABLE public.courses OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 41978)
-- Name: courses_course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses ALTER COLUMN course_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 41988)
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    department_id bigint NOT NULL,
    code character varying(255),
    created_at timestamp(6) without time zone,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    department_public_id uuid NOT NULL,
    description character varying(255),
    head_faculty_id character varying(255),
    is_deleted boolean NOT NULL,
    name character varying(255) NOT NULL,
    tenant_id uuid NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    parent_department_id bigint
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 41987)
-- Name: departments_department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departments ALTER COLUMN department_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 41996)
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    events_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    description character varying(255),
    events_public_id uuid NOT NULL,
    image_content oid,
    is_deleted boolean NOT NULL,
    posted_by character varying(255),
    tenant_id uuid,
    title character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by bigint
);


ALTER TABLE public.events OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 41995)
-- Name: events_events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events ALTER COLUMN events_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 42004)
-- Name: exam_schedules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exam_schedules (
    exam_schedule_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    course_id bigint,
    end_time time(6) without time zone,
    exam_date date,
    exam_id bigint,
    exam_schedule_public_id uuid,
    invigilator_id bigint,
    room_id bigint,
    start_time time(6) without time zone,
    tenant_id bigint
);


ALTER TABLE public.exam_schedules OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 42003)
-- Name: exam_schedules_exam_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exam_schedules ALTER COLUMN exam_schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_schedules_exam_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 42010)
-- Name: exams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams (
    exam_id bigint NOT NULL,
    academic_year_id bigint,
    batch_id bigint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    end_date timestamp(6) without time zone NOT NULL,
    name character varying(255) NOT NULL,
    exam_public_id uuid NOT NULL,
    is_deleted boolean NOT NULL,
    passing_marks double precision NOT NULL,
    semester_number integer NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    tenant_id uuid,
    total_marks double precision NOT NULL,
    exam_type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    CONSTRAINT exams_exam_type_check CHECK (((exam_type)::text = ANY ((ARRAY['MIDTERM'::character varying, 'FINAL'::character varying, 'QUIZ'::character varying, 'ASSIGNMENT'::character varying])::text[])))
);


ALTER TABLE public.exams OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 42009)
-- Name: exams_exam_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exams ALTER COLUMN exam_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_exam_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 42019)
-- Name: faculty; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.faculty (
    faculty_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    department_id bigint,
    designation character varying(255),
    employee_id character varying(255),
    employment_type character varying(255),
    faculty_public_id uuid,
    joining_date date,
    status character varying(255),
    tenant_id bigint,
    user_id bigint
);


ALTER TABLE public.faculty OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 42027)
-- Name: faculty_education; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.faculty_education (
    faculty_education_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    degree character varying(255),
    faculty_education_public_id uuid,
    faculty_id bigint,
    field_of_study character varying(255),
    grade_or_percentage character varying(255),
    institution character varying(255),
    passing_year integer,
    tenant_id bigint
);


ALTER TABLE public.faculty_education OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 42026)
-- Name: faculty_education_faculty_education_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.faculty_education ALTER COLUMN faculty_education_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faculty_education_faculty_education_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 42018)
-- Name: faculty_faculty_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.faculty ALTER COLUMN faculty_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faculty_faculty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 42035)
-- Name: faculty_work_experience; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.faculty_work_experience (
    work_experience_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    description character varying(255),
    faculty_id bigint,
    from_date date,
    organization character varying(255),
    role character varying(255),
    tenant_id bigint,
    to_date date,
    work_experience_public_id uuid
);


ALTER TABLE public.faculty_work_experience OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 42034)
-- Name: faculty_work_experience_work_experience_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.faculty_work_experience ALTER COLUMN work_experience_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faculty_work_experience_work_experience_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 42043)
-- Name: fee_invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fee_invoices (
    invoice_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    discount numeric(38,2),
    due_date date,
    fee_structure_id bigint,
    invoice_number character varying(255),
    invoice_public_id uuid,
    issue_date date,
    late_fee numeric(38,2),
    status character varying(255),
    student_id bigint,
    subtotal numeric(38,2),
    tenant_id bigint,
    total_amount numeric(38,2)
);


ALTER TABLE public.fee_invoices OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 42042)
-- Name: fee_invoices_invoice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fee_invoices ALTER COLUMN invoice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_invoices_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 42051)
-- Name: fee_payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fee_payments (
    payment_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    amount_paid numeric(38,2),
    collected_by bigint,
    gateway_response character varying(255),
    invoice_id bigint,
    payment_date date,
    payment_mode character varying(255),
    payment_public_id uuid,
    receipt_number character varying(255),
    status character varying(255),
    student_id bigint,
    tenant_id bigint,
    transaction_reference character varying(255)
);


ALTER TABLE public.fee_payments OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 42050)
-- Name: fee_payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fee_payments ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 42059)
-- Name: fee_structures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fee_structures (
    fee_structure_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    academic_year_id bigint,
    category character varying(255),
    due_date date,
    fee_name character varying(255),
    fee_structure_public_id uuid,
    late_fee_per_day numeric(38,2),
    program_id bigint,
    semester_number integer,
    tenant_id bigint,
    total_amount numeric(38,2)
);


ALTER TABLE public.fee_structures OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 42058)
-- Name: fee_structures_fee_structure_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fee_structures ALTER COLUMN fee_structure_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_structures_fee_structure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 42067)
-- Name: holidays; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.holidays (
    holiday_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    applies_to character varying(255),
    description character varying(255),
    holiday_date date,
    holiday_public_id uuid,
    holiday_type character varying(255),
    tenant_id bigint,
    title character varying(255)
);


ALTER TABLE public.holidays OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 42066)
-- Name: holidays_holiday_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.holidays ALTER COLUMN holiday_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holidays_holiday_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 42075)
-- Name: leave_applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leave_applications (
    leave_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    applicant_type character varying(255),
    applicant_user_id bigint,
    document_url character varying(255),
    from_date date,
    leave_public_id uuid,
    leave_type character varying(255),
    reason character varying(255),
    reviewed_at timestamp(6) with time zone,
    reviewed_by bigint,
    reviewer_remarks character varying(255),
    status character varying(255),
    tenant_id bigint,
    to_date date
);


ALTER TABLE public.leave_applications OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 42074)
-- Name: leave_applications_leave_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.leave_applications ALTER COLUMN leave_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_applications_leave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 42083)
-- Name: marks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marks (
    mark_id bigint NOT NULL,
    is_absent boolean,
    remarks character varying(255),
    course_id bigint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    entered_by bigint,
    exam_id bigint,
    grade character varying(255),
    grade_points double precision,
    is_deleted boolean NOT NULL,
    marks_obtained double precision,
    mark_public_id uuid NOT NULL,
    student_id bigint,
    tenant_id uuid,
    total_marks double precision,
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    is_withheld boolean
);


ALTER TABLE public.marks OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 42082)
-- Name: marks_mark_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marks ALTER COLUMN mark_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marks_mark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 42091)
-- Name: materials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.materials (
    materials_id bigint NOT NULL,
    course_code character varying(255),
    created_at timestamp(6) without time zone,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    description character varying(255),
    download_count integer NOT NULL,
    file_content oid,
    file_size bigint NOT NULL,
    file_type character varying(255),
    is_deleted boolean NOT NULL,
    last_updated_date timestamp(6) without time zone,
    material_code character varying(255),
    materials_public_id uuid NOT NULL,
    tenant_id uuid,
    title character varying(255),
    type character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    uploaded_by character varying(255),
    uploaded_date timestamp(6) without time zone
);


ALTER TABLE public.materials OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 42090)
-- Name: materials_materials_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.materials ALTER COLUMN materials_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materials_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 42099)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    notifications_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    is_deleted boolean NOT NULL,
    message text NOT NULL,
    notifications_public_id uuid NOT NULL,
    is_read boolean,
    tenant_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['EXAM'::character varying, 'RESULT'::character varying, 'ATTENDANCE'::character varying, 'EVENT'::character varying, 'GENERAL'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 42098)
-- Name: notifications_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN notifications_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 42108)
-- Name: otp_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.otp_tokens (
    otp_tokens_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone,
    is_deleted boolean NOT NULL,
    otp character varying(255) NOT NULL,
    otp_tokens_public_id uuid NOT NULL,
    purpose character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    used boolean NOT NULL,
    CONSTRAINT otp_tokens_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['EMAIL_VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying])::text[])))
);


ALTER TABLE public.otp_tokens OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 42107)
-- Name: otp_tokens_otp_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.otp_tokens ALTER COLUMN otp_tokens_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_tokens_otp_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 42117)
-- Name: permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissions (
    permission_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    action character varying(255),
    description character varying(255),
    module character varying(255),
    permission_public_id uuid,
    resource character varying(255),
    tenant_id bigint
);


ALTER TABLE public.permissions OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 42116)
-- Name: permissions_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permissions ALTER COLUMN permission_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 266 (class 1259 OID 42125)
-- Name: program_courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.program_courses (
    program_course_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    course_id bigint,
    is_elective boolean,
    is_mandatory boolean,
    program_course_public_id uuid,
    program_id bigint,
    semester_number integer,
    tenant_id bigint
);


ALTER TABLE public.program_courses OWNER TO postgres;

--
-- TOC entry 265 (class 1259 OID 42124)
-- Name: program_courses_program_course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.program_courses ALTER COLUMN program_course_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.program_courses_program_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 42131)
-- Name: programs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.programs (
    program_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    code character varying(255),
    degree_level character varying(255),
    department_id bigint,
    duration_years integer,
    is_active boolean,
    name character varying(255),
    program_public_id uuid,
    tenant_id bigint,
    total_credits integer,
    total_semesters integer
);


ALTER TABLE public.programs OWNER TO postgres;

--
-- TOC entry 267 (class 1259 OID 42130)
-- Name: programs_program_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.programs ALTER COLUMN program_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.programs_program_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 270 (class 1259 OID 42139)
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    role_permission_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    permission_id bigint,
    role_id bigint,
    role_permission_public_id uuid,
    tenant_id bigint
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- TOC entry 269 (class 1259 OID 42138)
-- Name: role_permissions_role_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role_permissions ALTER COLUMN role_permission_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_permissions_role_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 272 (class 1259 OID 42145)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    is_deleted boolean NOT NULL,
    is_system boolean NOT NULL,
    description character varying(255),
    role_public_id uuid NOT NULL,
    tenant_id uuid,
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    CONSTRAINT roles_name_check CHECK (((name)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'ADMIN'::character varying, 'HOD'::character varying, 'FACULTY'::character varying, 'STUDENT'::character varying, 'PARENT'::character varying, 'WARDEN'::character varying])::text[])))
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 271 (class 1259 OID 42144)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 274 (class 1259 OID 42154)
-- Name: rooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rooms (
    room_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    building character varying(255),
    capacity integer,
    floor integer,
    name character varying(255),
    room_number character varying(255),
    room_public_id uuid,
    room_type character varying(255),
    tenant_id bigint
);


ALTER TABLE public.rooms OWNER TO postgres;

--
-- TOC entry 273 (class 1259 OID 42153)
-- Name: rooms_room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rooms ALTER COLUMN room_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 276 (class 1259 OID 42162)
-- Name: students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students (
    student_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    admission_type character varying(255),
    batch_id bigint,
    current_semester integer,
    enrollment_date date,
    enrollment_number character varying(255),
    status character varying(255),
    student_public_id uuid,
    tenant_id bigint,
    user_id bigint
);


ALTER TABLE public.students OWNER TO postgres;

--
-- TOC entry 275 (class 1259 OID 42161)
-- Name: students_student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.students ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 277 (class 1259 OID 42169)
-- Name: tenants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tenants (
    tenant_public_id uuid NOT NULL,
    slug character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    domain character varying(255),
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    locale character varying(255) NOT NULL,
    logo_url character varying(255),
    max_faculty integer NOT NULL,
    max_students integer NOT NULL,
    name character varying(255) NOT NULL,
    primary_color character varying(255),
    subscription_expires_at timestamp(6) without time zone,
    plan character varying(255) NOT NULL,
    tenant_id bigint NOT NULL,
    timezone character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by bigint
);


ALTER TABLE public.tenants OWNER TO postgres;

--
-- TOC entry 279 (class 1259 OID 42177)
-- Name: timetable_slots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.timetable_slots (
    slot_id bigint NOT NULL,
    course_assignment_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by bigint,
    day_of_week character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    effective_from timestamp(6) without time zone NOT NULL,
    effective_to timestamp(6) without time zone,
    end_time character varying(255) NOT NULL,
    is_deleted boolean NOT NULL,
    recurrence character varying(255),
    room_id bigint NOT NULL,
    slot_type character varying(255),
    start_time character varying(255) NOT NULL,
    tenant_id uuid NOT NULL,
    slot_public_id uuid NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by bigint
);


ALTER TABLE public.timetable_slots OWNER TO postgres;

--
-- TOC entry 278 (class 1259 OID 42176)
-- Name: timetable_slots_slot_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.timetable_slots ALTER COLUMN slot_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timetable_slots_slot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 281 (class 1259 OID 42185)
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_role_id bigint NOT NULL,
    assigned_at timestamp(6) without time zone,
    context_id bigint,
    context_type character varying(255),
    created_at timestamp(6) without time zone,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    expires_at timestamp(6) without time zone,
    is_deleted boolean NOT NULL,
    tenant_id uuid,
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    user_role_public_id uuid NOT NULL,
    role_id bigint,
    user_id bigint
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- TOC entry 280 (class 1259 OID 42184)
-- Name: user_roles_user_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_roles ALTER COLUMN user_role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_roles_user_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 283 (class 1259 OID 42191)
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_sessions (
    session_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    deleted_at timestamp(6) with time zone,
    deleted_by bigint,
    is_deleted boolean,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    device_info character varying(255),
    expires_at timestamp(6) with time zone,
    ip_address character varying(255),
    refresh_token_hash character varying(255),
    revoked_at timestamp(6) with time zone,
    session_public_id uuid,
    tenant_id bigint,
    user_id bigint
);


ALTER TABLE public.user_sessions OWNER TO postgres;

--
-- TOC entry 282 (class 1259 OID 42190)
-- Name: user_sessions_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_sessions ALTER COLUMN session_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sessions_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 285 (class 1259 OID 42199)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    address_line1 character varying(255),
    avatar_url character varying(255),
    created_at timestamp(6) without time zone,
    created_by bigint,
    date_of_birth timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    email character varying(255),
    email_verified_at timestamp(6) without time zone,
    is_active boolean,
    first_name character varying(255),
    is_deleted boolean NOT NULL,
    last_login_at timestamp(6) without time zone,
    last_login_ip character varying(255),
    last_name character varying(255),
    locale character varying(255),
    mfa_enabled boolean,
    mfa_secret character varying(255),
    password_hash character varying(255),
    password_reset_expires_at timestamp(6) without time zone,
    password_reset_token character varying(255),
    phone character varying(255),
    phone_verified_at timestamp(6) without time zone,
    tenant_id uuid,
    timezone character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    user_public_id uuid NOT NULL,
    address_line2 character varying(255),
    city character varying(255),
    country character varying(255),
    gender character varying(255),
    postal_code character varying(255),
    state character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 284 (class 1259 OID 42198)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3875 (class 0 OID 41936)
-- Dependencies: 218
-- Data for Name: academic_years; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.academic_years (academic_year_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, academic_year_public_id, end_date, is_current, label, start_date, tenant_id) FROM stdin;
\.


--
-- TOC entry 3877 (class 0 OID 41942)
-- Dependencies: 220
-- Data for Name: announcements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.announcements (announcement_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, announcement_public_id, audience, audience_ref_id, content, expires_at, pinned_until, priority, published_at, tenant_id, title) FROM stdin;
\.


--
-- TOC entry 3879 (class 0 OID 41950)
-- Dependencies: 222
-- Data for Name: attendance_records; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attendance_records (attendance_record_id, attendance_record_public_id, created_at, created_by, deleted_at, deleted_by, is_deleted, marked_at, marked_by, remarks, session_id, status, student_id, tenant_id, updated_at, updated_by) FROM stdin;
\.


--
-- TOC entry 3881 (class 0 OID 41959)
-- Dependencies: 224
-- Data for Name: attendance_sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attendance_sessions (session_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, conducted_by, course_assignment_id, end_time, room_id, session_date, session_public_id, session_type, slot_id, start_time, tenant_id, topic_covered) FROM stdin;
\.


--
-- TOC entry 3883 (class 0 OID 41967)
-- Dependencies: 226
-- Data for Name: batches; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.batches (batch_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, academic_year_id, batch_public_id, class_teacher_id, current_semester, max_students, name, program_id, tenant_id) FROM stdin;
\.


--
-- TOC entry 3885 (class 0 OID 41973)
-- Dependencies: 228
-- Data for Name: course_assignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.course_assignments (course_assignment_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, academic_year_id, batch_id, course_assignment_public_id, course_id, faculty_id, is_primary, section, semester_number, tenant_id) FROM stdin;
\.


--
-- TOC entry 3887 (class 0 OID 41979)
-- Dependencies: 230
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses (course_id, is_active, code, name, course_public_id, created_at, created_by, credits, deleted_at, deleted_by, department_id, description, is_deleted, lab_hours_per_week, lecture_hours_per_week, course_type, tenant_id, tutorial_hours_per_week, updated_at, updated_by) FROM stdin;
\.


--
-- TOC entry 3889 (class 0 OID 41988)
-- Dependencies: 232
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departments (department_id, code, created_at, created_by, deleted_at, deleted_by, department_public_id, description, head_faculty_id, is_deleted, name, tenant_id, updated_at, updated_by, parent_department_id) FROM stdin;
\.


--
-- TOC entry 3891 (class 0 OID 41996)
-- Dependencies: 234
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.events (events_id, created_at, created_by, deleted_at, deleted_by, description, events_public_id, image_content, is_deleted, posted_by, tenant_id, title, updated_at, updated_by) FROM stdin;
\.


--
-- TOC entry 3893 (class 0 OID 42004)
-- Dependencies: 236
-- Data for Name: exam_schedules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exam_schedules (exam_schedule_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, course_id, end_time, exam_date, exam_id, exam_schedule_public_id, invigilator_id, room_id, start_time, tenant_id) FROM stdin;
\.


--
-- TOC entry 3895 (class 0 OID 42010)
-- Dependencies: 238
-- Data for Name: exams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exams (exam_id, academic_year_id, batch_id, created_at, created_by, deleted_at, deleted_by, end_date, name, exam_public_id, is_deleted, passing_marks, semester_number, start_date, tenant_id, total_marks, exam_type, updated_at, updated_by) FROM stdin;
\.


--
-- TOC entry 3897 (class 0 OID 42019)
-- Dependencies: 240
-- Data for Name: faculty; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.faculty (faculty_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, department_id, designation, employee_id, employment_type, faculty_public_id, joining_date, status, tenant_id, user_id) FROM stdin;
\.


--
-- TOC entry 3899 (class 0 OID 42027)
-- Dependencies: 242
-- Data for Name: faculty_education; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.faculty_education (faculty_education_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, degree, faculty_education_public_id, faculty_id, field_of_study, grade_or_percentage, institution, passing_year, tenant_id) FROM stdin;
\.


--
-- TOC entry 3901 (class 0 OID 42035)
-- Dependencies: 244
-- Data for Name: faculty_work_experience; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.faculty_work_experience (work_experience_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, description, faculty_id, from_date, organization, role, tenant_id, to_date, work_experience_public_id) FROM stdin;
\.


--
-- TOC entry 3903 (class 0 OID 42043)
-- Dependencies: 246
-- Data for Name: fee_invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fee_invoices (invoice_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, discount, due_date, fee_structure_id, invoice_number, invoice_public_id, issue_date, late_fee, status, student_id, subtotal, tenant_id, total_amount) FROM stdin;
\.


--
-- TOC entry 3905 (class 0 OID 42051)
-- Dependencies: 248
-- Data for Name: fee_payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fee_payments (payment_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, amount_paid, collected_by, gateway_response, invoice_id, payment_date, payment_mode, payment_public_id, receipt_number, status, student_id, tenant_id, transaction_reference) FROM stdin;
\.


--
-- TOC entry 3907 (class 0 OID 42059)
-- Dependencies: 250
-- Data for Name: fee_structures; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fee_structures (fee_structure_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, academic_year_id, category, due_date, fee_name, fee_structure_public_id, late_fee_per_day, program_id, semester_number, tenant_id, total_amount) FROM stdin;
\.


--
-- TOC entry 3909 (class 0 OID 42067)
-- Dependencies: 252
-- Data for Name: holidays; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.holidays (holiday_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, applies_to, description, holiday_date, holiday_public_id, holiday_type, tenant_id, title) FROM stdin;
\.


--
-- TOC entry 3911 (class 0 OID 42075)
-- Dependencies: 254
-- Data for Name: leave_applications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.leave_applications (leave_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, applicant_type, applicant_user_id, document_url, from_date, leave_public_id, leave_type, reason, reviewed_at, reviewed_by, reviewer_remarks, status, tenant_id, to_date) FROM stdin;
\.


--
-- TOC entry 3913 (class 0 OID 42083)
-- Dependencies: 256
-- Data for Name: marks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.marks (mark_id, is_absent, remarks, course_id, created_at, created_by, deleted_at, deleted_by, entered_by, exam_id, grade, grade_points, is_deleted, marks_obtained, mark_public_id, student_id, tenant_id, total_marks, updated_at, updated_by, is_withheld) FROM stdin;
\.


--
-- TOC entry 3915 (class 0 OID 42091)
-- Dependencies: 258
-- Data for Name: materials; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.materials (materials_id, course_code, created_at, created_by, deleted_at, deleted_by, description, download_count, file_content, file_size, file_type, is_deleted, last_updated_date, material_code, materials_public_id, tenant_id, title, type, updated_at, updated_by, uploaded_by, uploaded_date) FROM stdin;
\.


--
-- TOC entry 3917 (class 0 OID 42099)
-- Dependencies: 260
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (notifications_id, created_at, created_by, deleted_at, deleted_by, is_deleted, message, notifications_public_id, is_read, tenant_id, title, type, updated_at, updated_by, user_id) FROM stdin;
\.


--
-- TOC entry 3919 (class 0 OID 42108)
-- Dependencies: 262
-- Data for Name: otp_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.otp_tokens (otp_tokens_id, created_at, created_by, deleted_at, deleted_by, email, expires_at, is_deleted, otp, otp_tokens_public_id, purpose, updated_at, updated_by, used) FROM stdin;
\.


--
-- TOC entry 3921 (class 0 OID 42117)
-- Dependencies: 264
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permissions (permission_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, action, description, module, permission_public_id, resource, tenant_id) FROM stdin;
\.


--
-- TOC entry 3923 (class 0 OID 42125)
-- Dependencies: 266
-- Data for Name: program_courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.program_courses (program_course_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, course_id, is_elective, is_mandatory, program_course_public_id, program_id, semester_number, tenant_id) FROM stdin;
\.


--
-- TOC entry 3925 (class 0 OID 42131)
-- Dependencies: 268
-- Data for Name: programs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.programs (program_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, code, degree_level, department_id, duration_years, is_active, name, program_public_id, tenant_id, total_credits, total_semesters) FROM stdin;
\.


--
-- TOC entry 3927 (class 0 OID 42139)
-- Dependencies: 270
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role_permissions (role_permission_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, permission_id, role_id, role_permission_public_id, tenant_id) FROM stdin;
\.


--
-- TOC entry 3929 (class 0 OID 42145)
-- Dependencies: 272
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (role_id, name, created_at, created_by, deleted_at, deleted_by, is_deleted, is_system, description, role_public_id, tenant_id, updated_at, updated_by) FROM stdin;
1	SUPER_ADMIN	2026-03-18 17:58:12.014	\N	\N	\N	f	t	SUPER_ADMIN role	f7338bd1-e965-4a15-9ad3-f1fe84adba22	\N	2026-03-18 17:58:12.014	\N
2	ADMIN	2026-03-18 17:58:12.032	\N	\N	\N	f	t	ADMIN role	a4442703-3a2e-4842-aa1d-105f0beba14a	\N	2026-03-18 17:58:12.032	\N
3	HOD	2026-03-18 17:58:12.035	\N	\N	\N	f	t	HOD role	403e23a4-ef55-4f9c-91a6-03770435ef1f	\N	2026-03-18 17:58:12.035	\N
4	FACULTY	2026-03-18 17:58:12.037	\N	\N	\N	f	t	FACULTY role	d3af785b-60c0-4177-9c95-d1fcbc06550e	\N	2026-03-18 17:58:12.037	\N
5	STUDENT	2026-03-18 17:58:12.039	\N	\N	\N	f	t	STUDENT role	99141e77-7e49-4703-ad31-040893c3de61	\N	2026-03-18 17:58:12.039	\N
6	PARENT	2026-03-18 17:58:12.04	\N	\N	\N	f	t	PARENT role	884b8152-6c64-49ea-9877-494bf2035824	\N	2026-03-18 17:58:12.04	\N
7	WARDEN	2026-03-18 17:58:12.042	\N	\N	\N	f	t	WARDEN role	253f870c-3767-4024-9009-add70846b38c	\N	2026-03-18 17:58:12.042	\N
\.


--
-- TOC entry 3931 (class 0 OID 42154)
-- Dependencies: 274
-- Data for Name: rooms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rooms (room_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, building, capacity, floor, name, room_number, room_public_id, room_type, tenant_id) FROM stdin;
\.


--
-- TOC entry 3933 (class 0 OID 42162)
-- Dependencies: 276
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.students (student_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, admission_type, batch_id, current_semester, enrollment_date, enrollment_number, status, student_public_id, tenant_id, user_id) FROM stdin;
\.


--
-- TOC entry 3934 (class 0 OID 42169)
-- Dependencies: 277
-- Data for Name: tenants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tenants (tenant_public_id, slug, created_at, created_by, deleted_at, deleted_by, domain, is_active, is_deleted, locale, logo_url, max_faculty, max_students, name, primary_color, subscription_expires_at, plan, tenant_id, timezone, updated_at, updated_by) FROM stdin;
\.


--
-- TOC entry 3936 (class 0 OID 42177)
-- Dependencies: 279
-- Data for Name: timetable_slots; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.timetable_slots (slot_id, course_assignment_id, created_at, created_by, day_of_week, deleted_at, deleted_by, effective_from, effective_to, end_time, is_deleted, recurrence, room_id, slot_type, start_time, tenant_id, slot_public_id, updated_at, updated_by) FROM stdin;
\.


--
-- TOC entry 3938 (class 0 OID 42185)
-- Dependencies: 281
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (user_role_id, assigned_at, context_id, context_type, created_at, created_by, deleted_at, deleted_by, expires_at, is_deleted, tenant_id, updated_at, updated_by, user_role_public_id, role_id, user_id) FROM stdin;
\.


--
-- TOC entry 3940 (class 0 OID 42191)
-- Dependencies: 283
-- Data for Name: user_sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_sessions (session_id, created_at, created_by, deleted_at, deleted_by, is_deleted, updated_at, updated_by, device_info, expires_at, ip_address, refresh_token_hash, revoked_at, session_public_id, tenant_id, user_id) FROM stdin;
\.


--
-- TOC entry 3942 (class 0 OID 42199)
-- Dependencies: 285
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, address_line1, avatar_url, created_at, created_by, date_of_birth, deleted_at, deleted_by, email, email_verified_at, is_active, first_name, is_deleted, last_login_at, last_login_ip, last_name, locale, mfa_enabled, mfa_secret, password_hash, password_reset_expires_at, password_reset_token, phone, phone_verified_at, tenant_id, timezone, updated_at, updated_by, user_public_id, address_line2, city, country, gender, postal_code, state) FROM stdin;
\.


--
-- TOC entry 3948 (class 0 OID 0)
-- Dependencies: 217
-- Name: academic_years_academic_year_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.academic_years_academic_year_id_seq', 1, false);


--
-- TOC entry 3949 (class 0 OID 0)
-- Dependencies: 219
-- Name: announcements_announcement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.announcements_announcement_id_seq', 1, false);


--
-- TOC entry 3950 (class 0 OID 0)
-- Dependencies: 221
-- Name: attendance_records_attendance_record_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attendance_records_attendance_record_id_seq', 1, false);


--
-- TOC entry 3951 (class 0 OID 0)
-- Dependencies: 223
-- Name: attendance_sessions_session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attendance_sessions_session_id_seq', 1, false);


--
-- TOC entry 3952 (class 0 OID 0)
-- Dependencies: 225
-- Name: batches_batch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.batches_batch_id_seq', 1, false);


--
-- TOC entry 3953 (class 0 OID 0)
-- Dependencies: 227
-- Name: course_assignments_course_assignment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_assignments_course_assignment_id_seq', 1, false);


--
-- TOC entry 3954 (class 0 OID 0)
-- Dependencies: 229
-- Name: courses_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_course_id_seq', 1, false);


--
-- TOC entry 3955 (class 0 OID 0)
-- Dependencies: 231
-- Name: departments_department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departments_department_id_seq', 1, false);


--
-- TOC entry 3956 (class 0 OID 0)
-- Dependencies: 233
-- Name: events_events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.events_events_id_seq', 1, false);


--
-- TOC entry 3957 (class 0 OID 0)
-- Dependencies: 235
-- Name: exam_schedules_exam_schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exam_schedules_exam_schedule_id_seq', 1, false);


--
-- TOC entry 3958 (class 0 OID 0)
-- Dependencies: 237
-- Name: exams_exam_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exams_exam_id_seq', 1, false);


--
-- TOC entry 3959 (class 0 OID 0)
-- Dependencies: 241
-- Name: faculty_education_faculty_education_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.faculty_education_faculty_education_id_seq', 1, false);


--
-- TOC entry 3960 (class 0 OID 0)
-- Dependencies: 239
-- Name: faculty_faculty_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.faculty_faculty_id_seq', 1, false);


--
-- TOC entry 3961 (class 0 OID 0)
-- Dependencies: 243
-- Name: faculty_work_experience_work_experience_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.faculty_work_experience_work_experience_id_seq', 1, false);


--
-- TOC entry 3962 (class 0 OID 0)
-- Dependencies: 245
-- Name: fee_invoices_invoice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fee_invoices_invoice_id_seq', 1, false);


--
-- TOC entry 3963 (class 0 OID 0)
-- Dependencies: 247
-- Name: fee_payments_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fee_payments_payment_id_seq', 1, false);


--
-- TOC entry 3964 (class 0 OID 0)
-- Dependencies: 249
-- Name: fee_structures_fee_structure_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fee_structures_fee_structure_id_seq', 1, false);


--
-- TOC entry 3965 (class 0 OID 0)
-- Dependencies: 251
-- Name: holidays_holiday_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.holidays_holiday_id_seq', 1, false);


--
-- TOC entry 3966 (class 0 OID 0)
-- Dependencies: 253
-- Name: leave_applications_leave_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.leave_applications_leave_id_seq', 1, false);


--
-- TOC entry 3967 (class 0 OID 0)
-- Dependencies: 255
-- Name: marks_mark_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.marks_mark_id_seq', 1, false);


--
-- TOC entry 3968 (class 0 OID 0)
-- Dependencies: 257
-- Name: materials_materials_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.materials_materials_id_seq', 1, false);


--
-- TOC entry 3969 (class 0 OID 0)
-- Dependencies: 259
-- Name: notifications_notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_notifications_id_seq', 1, false);


--
-- TOC entry 3970 (class 0 OID 0)
-- Dependencies: 261
-- Name: otp_tokens_otp_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.otp_tokens_otp_tokens_id_seq', 1, false);


--
-- TOC entry 3971 (class 0 OID 0)
-- Dependencies: 263
-- Name: permissions_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permissions_permission_id_seq', 1, false);


--
-- TOC entry 3972 (class 0 OID 0)
-- Dependencies: 265
-- Name: program_courses_program_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.program_courses_program_course_id_seq', 1, false);


--
-- TOC entry 3973 (class 0 OID 0)
-- Dependencies: 267
-- Name: programs_program_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.programs_program_id_seq', 1, false);


--
-- TOC entry 3974 (class 0 OID 0)
-- Dependencies: 269
-- Name: role_permissions_role_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_permissions_role_permission_id_seq', 1, false);


--
-- TOC entry 3975 (class 0 OID 0)
-- Dependencies: 271
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 7, true);


--
-- TOC entry 3976 (class 0 OID 0)
-- Dependencies: 273
-- Name: rooms_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rooms_room_id_seq', 1, false);


--
-- TOC entry 3977 (class 0 OID 0)
-- Dependencies: 275
-- Name: students_student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.students_student_id_seq', 1, false);


--
-- TOC entry 3978 (class 0 OID 0)
-- Dependencies: 278
-- Name: timetable_slots_slot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.timetable_slots_slot_id_seq', 1, false);


--
-- TOC entry 3979 (class 0 OID 0)
-- Dependencies: 280
-- Name: user_roles_user_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_roles_user_role_id_seq', 1, false);


--
-- TOC entry 3980 (class 0 OID 0)
-- Dependencies: 282
-- Name: user_sessions_session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_sessions_session_id_seq', 1, false);


--
-- TOC entry 3981 (class 0 OID 0)
-- Dependencies: 284
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1, false);


--
-- TOC entry 3626 (class 2606 OID 41940)
-- Name: academic_years academic_years_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.academic_years
    ADD CONSTRAINT academic_years_pkey PRIMARY KEY (academic_year_id);


--
-- TOC entry 3628 (class 2606 OID 41948)
-- Name: announcements announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (announcement_id);


--
-- TOC entry 3630 (class 2606 OID 41957)
-- Name: attendance_records attendance_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance_records
    ADD CONSTRAINT attendance_records_pkey PRIMARY KEY (attendance_record_id);


--
-- TOC entry 3634 (class 2606 OID 41965)
-- Name: attendance_sessions attendance_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance_sessions
    ADD CONSTRAINT attendance_sessions_pkey PRIMARY KEY (session_id);


--
-- TOC entry 3636 (class 2606 OID 41971)
-- Name: batches batches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batches
    ADD CONSTRAINT batches_pkey PRIMARY KEY (batch_id);


--
-- TOC entry 3638 (class 2606 OID 41977)
-- Name: course_assignments course_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_assignments
    ADD CONSTRAINT course_assignments_pkey PRIMARY KEY (course_assignment_id);


--
-- TOC entry 3640 (class 2606 OID 41986)
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (course_id);


--
-- TOC entry 3644 (class 2606 OID 41994)
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (department_id);


--
-- TOC entry 3648 (class 2606 OID 42002)
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (events_id);


--
-- TOC entry 3652 (class 2606 OID 42008)
-- Name: exam_schedules exam_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_schedules
    ADD CONSTRAINT exam_schedules_pkey PRIMARY KEY (exam_schedule_id);


--
-- TOC entry 3654 (class 2606 OID 42017)
-- Name: exams exams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_pkey PRIMARY KEY (exam_id);


--
-- TOC entry 3660 (class 2606 OID 42033)
-- Name: faculty_education faculty_education_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.faculty_education
    ADD CONSTRAINT faculty_education_pkey PRIMARY KEY (faculty_education_id);


--
-- TOC entry 3658 (class 2606 OID 42025)
-- Name: faculty faculty_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT faculty_pkey PRIMARY KEY (faculty_id);


--
-- TOC entry 3662 (class 2606 OID 42041)
-- Name: faculty_work_experience faculty_work_experience_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.faculty_work_experience
    ADD CONSTRAINT faculty_work_experience_pkey PRIMARY KEY (work_experience_id);


--
-- TOC entry 3664 (class 2606 OID 42049)
-- Name: fee_invoices fee_invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fee_invoices
    ADD CONSTRAINT fee_invoices_pkey PRIMARY KEY (invoice_id);


--
-- TOC entry 3666 (class 2606 OID 42057)
-- Name: fee_payments fee_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fee_payments
    ADD CONSTRAINT fee_payments_pkey PRIMARY KEY (payment_id);


--
-- TOC entry 3668 (class 2606 OID 42065)
-- Name: fee_structures fee_structures_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fee_structures
    ADD CONSTRAINT fee_structures_pkey PRIMARY KEY (fee_structure_id);


--
-- TOC entry 3670 (class 2606 OID 42073)
-- Name: holidays holidays_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.holidays
    ADD CONSTRAINT holidays_pkey PRIMARY KEY (holiday_id);


--
-- TOC entry 3672 (class 2606 OID 42081)
-- Name: leave_applications leave_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_applications
    ADD CONSTRAINT leave_applications_pkey PRIMARY KEY (leave_id);


--
-- TOC entry 3674 (class 2606 OID 42089)
-- Name: marks marks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT marks_pkey PRIMARY KEY (mark_id);


--
-- TOC entry 3678 (class 2606 OID 42097)
-- Name: materials materials_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT materials_pkey PRIMARY KEY (materials_id);


--
-- TOC entry 3682 (class 2606 OID 42106)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notifications_id);


--
-- TOC entry 3686 (class 2606 OID 42115)
-- Name: otp_tokens otp_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_tokens
    ADD CONSTRAINT otp_tokens_pkey PRIMARY KEY (otp_tokens_id);


--
-- TOC entry 3690 (class 2606 OID 42123)
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (permission_id);


--
-- TOC entry 3692 (class 2606 OID 42129)
-- Name: program_courses program_courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.program_courses
    ADD CONSTRAINT program_courses_pkey PRIMARY KEY (program_course_id);


--
-- TOC entry 3694 (class 2606 OID 42137)
-- Name: programs programs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_pkey PRIMARY KEY (program_id);


--
-- TOC entry 3696 (class 2606 OID 42143)
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_permission_id);


--
-- TOC entry 3698 (class 2606 OID 42152)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 3702 (class 2606 OID 42160)
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (room_id);


--
-- TOC entry 3704 (class 2606 OID 42168)
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (student_id);


--
-- TOC entry 3706 (class 2606 OID 42175)
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (tenant_id);


--
-- TOC entry 3712 (class 2606 OID 42183)
-- Name: timetable_slots timetable_slots_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timetable_slots
    ADD CONSTRAINT timetable_slots_pkey PRIMARY KEY (slot_id);


--
-- TOC entry 3716 (class 2606 OID 42235)
-- Name: user_roles uk4v62rjfiiru5me1ge7ki58u1d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT uk4v62rjfiiru5me1ge7ki58u1d UNIQUE (user_role_public_id);


--
-- TOC entry 3724 (class 2606 OID 42237)
-- Name: users uk5yqpf15po5ol6usm6bj86xtja; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk5yqpf15po5ol6usm6bj86xtja UNIQUE (user_public_id);


--
-- TOC entry 3688 (class 2606 OID 42223)
-- Name: otp_tokens uk6bhjldnv43x7hrpkd8xxdt10b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_tokens
    ADD CONSTRAINT uk6bhjldnv43x7hrpkd8xxdt10b UNIQUE (otp_tokens_public_id);


--
-- TOC entry 3646 (class 2606 OID 42211)
-- Name: departments uk7l4fkq39jguhl2ownoj54w8kk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT uk7l4fkq39jguhl2ownoj54w8kk UNIQUE (department_public_id);


--
-- TOC entry 3632 (class 2606 OID 42207)
-- Name: attendance_records uk7u5j3bw93b4m86wo9ev7555u9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance_records
    ADD CONSTRAINT uk7u5j3bw93b4m86wo9ev7555u9 UNIQUE (attendance_record_public_id);


--
-- TOC entry 3708 (class 2606 OID 42227)
-- Name: tenants uk91uwdubak6t8agwfh6oxeigh8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT uk91uwdubak6t8agwfh6oxeigh8 UNIQUE (tenant_public_id);


--
-- TOC entry 3714 (class 2606 OID 42231)
-- Name: timetable_slots uka5s8f69aeykpgufdbowcfqdcn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timetable_slots
    ADD CONSTRAINT uka5s8f69aeykpgufdbowcfqdcn UNIQUE (slot_public_id);


--
-- TOC entry 3676 (class 2606 OID 42217)
-- Name: marks ukau86xc120fibxm1415mlollnh; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT ukau86xc120fibxm1415mlollnh UNIQUE (mark_public_id);


--
-- TOC entry 3700 (class 2606 OID 42225)
-- Name: roles ukd02k3pa4y74111on84rp0o8pl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukd02k3pa4y74111on84rp0o8pl UNIQUE (role_public_id);


--
-- TOC entry 3656 (class 2606 OID 42215)
-- Name: exams ukf8i5qww34moc0m94npa8opfql; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT ukf8i5qww34moc0m94npa8opfql UNIQUE (exam_public_id);


--
-- TOC entry 3642 (class 2606 OID 42209)
-- Name: courses ukjqeejgub2xr8n7v516d4to29v; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT ukjqeejgub2xr8n7v516d4to29v UNIQUE (course_public_id);


--
-- TOC entry 3684 (class 2606 OID 42221)
-- Name: notifications ukk75ncrga4q8adi8t0cnmrsyo5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT ukk75ncrga4q8adi8t0cnmrsyo5 UNIQUE (notifications_public_id);


--
-- TOC entry 3710 (class 2606 OID 42229)
-- Name: tenants ukkn82rs0p55luybrg4n7x7di8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT ukkn82rs0p55luybrg4n7x7di8 UNIQUE (slug);


--
-- TOC entry 3650 (class 2606 OID 42213)
-- Name: events ukmxj0jmca1v6jha7vo2maun5r3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT ukmxj0jmca1v6jha7vo2maun5r3 UNIQUE (events_public_id);


--
-- TOC entry 3718 (class 2606 OID 42233)
-- Name: user_roles ukq5aecepppguf22pbwg5gawp5j; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT ukq5aecepppguf22pbwg5gawp5j UNIQUE (tenant_id, user_id, role_id, context_type, context_id);


--
-- TOC entry 3680 (class 2606 OID 42219)
-- Name: materials ukrcxu0uxr3xjbm33c8dmri80gn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT ukrcxu0uxr3xjbm33c8dmri80gn UNIQUE (materials_public_id);


--
-- TOC entry 3720 (class 2606 OID 42189)
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_role_id);


--
-- TOC entry 3722 (class 2606 OID 42197)
-- Name: user_sessions user_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (session_id);


--
-- TOC entry 3726 (class 2606 OID 42205)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 3727 (class 2606 OID 42238)
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- TOC entry 3728 (class 2606 OID 42243)
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(user_id);


-- Completed on 2026-03-19 01:25:45 IST

--
-- PostgreSQL database dump complete
--

\unrestrict DGp3k5VApZG8XP99JTJm4l0Pe4h7OkaXtC9j0iRe1vBeb8HmxZfOX8lIj0mE7BN

